src/Entity/Post.php
<?php

namespace App\Entity;

use App\Repository\PostRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PostRepository::class)]
class Post
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $titulo = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $likes = null;

    #[ORM\Column(length: 254, nullable: true)]
    private ?string $foto = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $fecha_publicacion = null;

    #[ORM\Column(length: 254)]
    private ?string $contenido = null;

    #[ORM\ManyToOne(inversedBy: 'post')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Usuario $usuario = null;

    #[ORM\OneToMany(mappedBy: 'post', targetEntity: Comentario::class)]
    private Collection $comentario;

    public function __construct()
    {
        $this->comentario = new ArrayCollection();

        $this -> likes = '';
        $this -> fecha_publicacion = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitulo(): ?string
    {
        return $this->titulo;
    }

    public function setTitulo(string $titulo): self
    {
        $this->titulo = $titulo;

        return $this;
    }

    public function getLikes(): ?string
    {
        return $this->likes;
    }

    public function setLikes(?string $likes): self
    {
        $this->likes = $likes;

        return $this;
    }

    public function getFoto(): ?string
    {
        return $this->foto;
    }

    public function setFoto(?string $foto): self
    {
        $this->foto = $foto;

        return $this;
    }

    public function getFechaPublicacion(): ?\DateTimeInterface
    {
        return $this->fecha_publicacion;
    }

    public function setFechaPublicacion(\DateTimeInterface $fecha_publicacion): self
    {
        $this->fecha_publicacion = $fecha_publicacion;

        return $this;
    }

    public function getContenido(): ?string
    {
        return $this->contenido;
    }

    public function setContenido(string $contenido): self
    {
        $this->contenido = $contenido;

        return $this;
    }

    public function getUsuario(): ?Usuario
    {
        return $this->usuario;
    }

    public function setUsuario(?Usuario $usuario): self
    {
        $this->usuario = $usuario;

        return $this;
    }

    /**
     * @return Collection<int, Comentario>
     */
    public function getComentario(): Collection
    {
        return $this->comentario;
    }

    public function addComentario(Comentario $comentario): self
    {
        if (!$this->comentario->contains($comentario)) {
            $this->comentario->add($comentario);
            $comentario->setPost($this);
        }

        return $this;
    }

    public function removeComentario(Comentario $comentario): self
    {
        if ($this->comentario->removeElement($comentario)) {
            // set the owning side to null (unless already changed)
            if ($comentario->getPost() === $this) {
                $comentario->setPost(null);
            }
        }

        return $this;
    }
}

src/Form/PostType.php
<?php

namespace App\Form;

use App\Entity\Post;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class PostType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('titulo', TextType::class)
            //->add('likes')
            ->add('foto', FileType::class, [
                'label' => 'Selecciones una imagen',
                'mapped' => false,
                'required' => false,
            ])
            //->add('fecha_publicacion')
            ->add('contenido', TextareaType::class)
            //->add('usuario')
            ->add('Guardar', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use App\Entity\Comentario;
use App\Entity\Post;
use App\Form\ComentarioType;
use App\Form\PostType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\Exception\FileException;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

class PostController extends AbstractController
{
    #[Route('/post', name: 'post')]
    public function index(Request $request, EntityManagerInterface $entityManager, SluggerInterface $slugger): Response
    {
        $post = new Post();
        $formulario = $this -> createForm(PostType::class, $post);
        $formulario -> handleRequest($request);

        if ($formulario->isSubmitted() && $formulario->isValid()){
            // Obtenemos al Usuario
            $usuario = $this -> getUser();
            $post -> setUsuario($usuario);

            /** @var UploadedFile $fotoArchivo */
            $fotoArchivo = $formulario->get('foto')->getData();
            if ($fotoArchivo) {
                $fotoOriginal = pathinfo($fotoArchivo->getClientOriginalName(), PATHINFO_FILENAME);
                // this is needed to safely include the file name as part of the URL
                $safeFilename = $slugger->slug($fotoOriginal);
                $newFilename = $safeFilename.'-'.uniqid().'.'.$fotoArchivo->guessExtension();
                // Move the file to the directory where brochures are stored
                try {
                    $fotoArchivo->move(
                        $this->getParameter('foto_directory'),
                        $newFilename
                    );
                } catch (FileException $e) {
                    throw new \Exception('Ocurrio un error al cargar la FOTO');
                }
                // updates the 'brochureFilename' property to store the PDF file name
                // instead of its contents
                $post->setFoto($newFilename);
            }

            $entityManager -> persist($post);
            $entityManager -> flush();

            return $this -> redirectToRoute('principal');
        }
        return $this->render('post/index.html.twig', [
            'formulario' => $formulario-> createView(),
        ]);
    }

    #[Route('/post/{id}', name:'verPost')]
    public function verPost($id, EntityManagerInterface $entityManager, Request $request){

        $post = $entityManager->getRepository(Post::class)->find($id);

        $comentario = new Comentario();
        $consultaComentario = $entityManager->getRepository(Comentario::class)->BuscarComentarioUnPost($post->getId());

        $formulario = $this->createForm(ComentarioType::class, $comentario);
        $formulario->handleRequest($request);

        if ($formulario->isSubmitted() && $formulario->isValid()){
            $usuario = $this->getUser();
            $comentario->setPost($post);
            $comentario->setUsuario($usuario);
            $entityManager->persist($comentario);
            $entityManager->flush();

            $this->addFlash('success', Comentario::COMENTARIO_AGREGADO_EXITOSAMENTE);
            return $this->redirectToRoute('verPost',[
               'id' => $post->getId()
            ]);
        }

        return $this->render('post/verPost.html.twig',[
            'post'=>$post,
            'formulario' => $formulario->createView(),
            'comentarios' => $consultaComentario
        ]);
    }

    #[Route('/mi_post', name:'miPost')]
    public function miPost(EntityManagerInterface $entityManager){

        $usuario = $this->getUser();
        $post = $entityManager->getRepository(Post::class)->findBy(['usuario'=>$usuario]);

        return $this->render('post/miPost.html.twig',[
            'post' => $post
        ]);
    }
}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Nuevo Post|{{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}

    <div class="container h-100">
        <div class="row h-100 justify-content-center align-items-center">
            <div class="col-6 bg-white rounded my-3 p-5">
                <h1>Registrar Post</h1>
                {{ form(formulario) }}
            </div>
        </div>
    </div>
    
{% endblock %}

templates/post/miPost.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Mis Post|{{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}
    {{ dump(post) }}


{% endblock %}

templates/post/verPost.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Ver Post|{{ parent() }}
{% endblock %}

{% block body %}
    {{ parent() }}

    {#{{ dump(post) }}#}

    <div class="container bg-white rounded my-3 p-4">
        <div class="d-flex bd-highlight">
            <div class="p-2 flex-grow-1 bd-highlight">
                <h3>{{ post.titulo }}</h3>
                <div class="my-3" style="color: blue;">
                    <i class="fa fa-thumbs-up"></i>
                    <strong># Likes</strong>
                </div>
                <div style="color: green;">
                    <i class="far fa-clock"></i>
                    <strong>Fecha de publicacion: {{ post.fechaPublicacion|date('d-m-Y') }}</strong>
                </div>
            </div>
            <div class="p-2 bd-highlight">
                <div class="align-self-center">
                    <img class="rounded" src="{{ asset('uploads/foto/'~post.foto) }}" width="150px" alt="">
                </div>
            </div>
        </div>
        <hr>
        <div class="text-justify my-3">
            {{ post.contenido }}
        </div>
        <hr>
    </div>

    <div class="container p-3">
        {{ form(formulario) }}

        <h3>Comentarios</h3>
        {% for comentario in comentarios %}
            <div class="rounded bg-white my-2 p-3 border">
                <h5>{{ comentario.nombre}} Dijo:</h5>
                <div class="w-100">{{ comentario.comentario }}</div>
            </div>
        {% endfor %}
    </div>

    {{ dump(comentarios) }}

{% endblock %}